terraform {
  required_version = ">= 1.0.0"
  required_providers {
    b2 = {
      source = "Backblaze/b2"
    }
  }
}

resource "b2_application_key" "key" {
  key_name  = var.name
  bucket_id = var.bucket_id

  capabilities = [
    "listFiles",
    "readFiles",
    "writeFiles",
    "deleteFiles",
    "listBuckets",
  ]
}

resource "local_file" "credentials" {
  filename = "${path.root}/credentials/backup/${var.filename}"
  content  = <<EOF
#!/usr/bin/env bash

# Auto-generated by Terraform

export B2_APPLICATION_KEY_NAME="${b2_application_key.key.key_name}"
export B2_APPLICATION_KEY_ID="${b2_application_key.key.application_key_id}"
export B2_APPLICATION_KEY="${b2_application_key.key.application_key}"
EOF
}
