require "./align.coffee"
require "./cycleSelection.coffee"
require "./deleteLine.coffee"
require "./duplicate.coffee"
require "./joinLinesUp.coffee"
require "./numberStartingWith.coffee"
require "./removeInlineWhitespace.coffee"
require "./shellCommand.coffee"
