#!/usr/bin/env bash

set -euo pipefail

WACOMSCREEN=$(xrandr --listactivemonitors | grep -Eo '(DisplayPort|DP|HDMI|DVI)-[0-9]' | head -1)
echo "Using screen connected to $WACOMSCREEN"

touch="Wacom Intuos Pro M Finger touch"
pen="Wacom Intuos Pro M Pen stylus"
eraser="Wacom Intuos Pro M Pen eraser"
cursor="Wacom Intuos Pro M Pen cursor"
pad="Wacom Intuos Pro M Pad pad"

xsetwacom set "$touch"  MapToOutput "$WACOMSCREEN"
xsetwacom set "$pen"    MapToOutput "$WACOMSCREEN"
xsetwacom set "$eraser" MapToOutput "$WACOMSCREEN"
xsetwacom set "$cursor" MapToOutput "$WACOMSCREEN"
xsetwacom set "$pad"    MapToOutput "$WACOMSCREEN"

xsetwacom set "$touch" touch off



configure_stylus_buttons() {

    # front button
    xsetwacom set "$pen" "Button" "2" "button +3" # right click

    # back button
    xsetwacom set "$pen" "Button" "3" "button +2 " # middle click
}
configure_stylus_buttons



configure_pad_buttons() {

    # Top column
    xsetwacom set "$pad" Button 2  "key +space"        # Krita: pan
    xsetwacom set "$pad" Button 3  "key +ctrl +space"  # Krita: zoom
    xsetwacom set "$pad" Button 8  "key +shift +space" # Krita: rotate
    xsetwacom set "$pad" Button 9  "key +ctrl z -ctrl" # Undo

    # Center circle
    # xsetwacom set "$pad" Button 1  "key 1"

    # Bottom column
    xsetwacom set "$pad" Button 10 "key l" # Krita: lasso (in my config)
    xsetwacom set "$pad" Button 11 "key +ctrl +shift a" # Krita: deselect all
    # xsetwacom set "$pad" Button 12 "key c"
    # xsetwacom set "$pad" Button 13 "key d"
}
configure_pad_buttons



print_settings() {
    {
        xsetwacom -s get "$touch"  all
        xsetwacom -s get "$pen"    all
        xsetwacom -s get "$eraser" all
        xsetwacom -s get "$cursor" all
        xsetwacom -s get "$pad"    all
    } 2>&1 | grep -v 'does not exist' | perl -pe 's/(Pro M )([^"]+)(")/\1\033[34m\2\033[m\3/g'
}
print_settings
