#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

source "$SCRIPT_DIR/credentials.source"

(
    set -x
    restic backup                                    \
        --exclude-file       "$SCRIPT_DIR/excludes"  \
        --iexclude-file      "$SCRIPT_DIR/iexcludes" \
        --host               "$RESTIC_HOSTNAME"      \
        --exclude-if-present ".nobackup"             \
        --with-atime                                 \
        --one-file-system                            \
        "$HOME"                                      \
        "$@"
)

