#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

source "$SCRIPT_DIR/credentials.source"

(
    set -x

    restic backup                                    \
        --exclude-file       "$SCRIPT_DIR/excludes"  \
        --iexclude-file      "$SCRIPT_DIR/iexcludes" \
        --host               "$RESTIC_HOSTNAME"      \
        --exclude-if-present ".nobackup"             \
        --with-atime                                 \
        --one-file-system                            \
        --compression max                            \
        --cleanup-cache                              \
        "$HOME"                                      \
        "$@"

    restic forget                 \
        --host "$RESTIC_HOSTNAME" \
        --keep-within-monthly 1y  \
        --keep-within-weekly 1m   \
        --keep-within-daily 7d    \
        --keep-within 1d
)

"$SCRIPT_DIR"/copy_to_pi
